## Load USPS on Python 3.x

In [7]:
from PIL import Image
import os
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential
import pickle
import gzip
import scipy.sparse
import numpy as np
from math import exp

Using TensorFlow backend.


In [5]:
USPSMat  = []
USPSTar  = []
curPath  = 'USPSdata/Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)
USPS_Mat = np.array(USPSMat)
USPS_Tar = np.array(USPSTar)

In [8]:
num_classes = 10
USPS_Target = np.array(USPSTar)
USPS_Tar = keras.utils.to_categorical(USPSTar, num_classes)

In [206]:
import numpy as np
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')
n_train = 60000
n_test = 10000
indices = range(len(mnist.data))
train_idx = range(0,n_train)
test_idx = range(n_train+1,n_train+n_test)
X_train, y_train = mnist.data[train_idx], mnist.target[train_idx]
X_test, y_test = mnist.data[test_idx], mnist.target[test_idx]

# SVM
classifier1 = SVC(kernel='rbf', C=2, gamma = 0.05);
classifier1.fit(X_train, y_train)
y_pred_SVC1 = classifier2.predict(X_test)

 # SVM
classifier1 = SVC(kernel='linear', C=2, gamma = 0.05);
classifier1.fit(X_train, y_train)
y_pred_SVC21 = classifier2.predict(X_test)
y_pred_SVC22 = classifier2.predict(X_test)

out_mnist = confusion_matrix(y_pred_svc, y_test)
print(" MNIST - confusion matrix using SVC :")
print(out_mnist)

out_usps = confusion_matrix(y_pred_svc2, USPS_Target)
print(" USPS - confusion matrix using SVC :")
print(out_usps)

#RandomForestClassifier
classifier2 = RandomForestClassifier(n_estimators = 30);
classifier2.fit(X_train, y_train)
y_pred_RFC = classifier2.predict(X_test)
y_pred_RFC2 = classifier2.predict(USPS_Mat)

acc_mnist = accuracy_score(y_pred_RFC, y_test)
out_mnist = confusion_matrix(y_pred_RFC, y_test)
print(" MNIST - confusion matrix using RFC :")
print(out_mnist)
print(" ")
acc_usps = accuracy_score(y_pred_RFC2, USPS_Target)
out_usps = confusion_matrix(y_pred_RFC2, USPS_Target)
print(" USPS - confusion matrix using RFC :")
print(out_usps)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)


 MNIST - confusion matrix using RFC :
[[ 970    0    4    0    1    5    9    2    6    3]
 [   0 1122    1    0    0    1    3    5    1    5]
 [   1    2  997   11    2    1    1   22    4    1]
 [   0    4    7  966    0   14    0    2   11    9]
 [   0    2    4    0  947    2    2    1    3   15]
 [   1    2    1    7    0  851    4    0    7    5]
 [   3    2    1    0    5    7  936    1    4    1]
 [   1    0    9   12    0    2    0  981    4    4]
 [   3    1    7   12    2    4    3    3  925    9]
 [   0    0    1    2   25    5    0   11    9  957]]
 
 USPS - confusion matrix using RFC :
[[  46    0   14   21    0   13   48    0   18    2]
 [ 157  506  417  109  210  302  286  546  286  332]
 [   9    2   68   25   18    7   63    7   25   15]
 [   0    0    1    8    0    1    0    0    2    0]
 [  91   43   53  133  148   42   58   44  164   66]
 [ 401  102  240  446  220  507  354  317  676  305]
 [   0    0    2    0    0    0    4    0    0    0]
 [1296 1347 1204 1258

In [209]:
acc_usps = accuracy_score(y_pred_RFC2, USPS_Target)
print("Accuracy using MNIST is : ",+acc_usps)
acc_mnist

Accuracy using MNIST is :  0.11865593279663983


0.9652965296529653

In [9]:
def oneHotIt(Y):
    m = Y.shape[0]
    targets = np.array(Y)
    OHX = scipy.sparse.csr_matrix((np.ones(m), (Y, np.array(range(m)))))
    OHX = np.array(OHX.todense()).T
    n_lables = 10
    targets = np.array(Y)
    for i in range(50000):
        ohm = np.zeros((targets.shape[0],n_lables))
        ohm[np.arange(targets.shape[0]),targets]=1
    return OHX
def logistic_regression(x_train, real_target,ini_weit):
    a = np.zeros((10))
    for row in range(x_train.shape[0]):
        current_row = x_train[row]
        current_target = real_target[row]
        local_sum = 0
        Bias = 0
        for i in range(10):
            a[i] = np.dot(ini_weit[i],current_row) + Bias
            local_sum = local_sum + np.exp(a[i])
        y = np.zeros((10))
        for j in range(10):
            y[i] = (np.exp(a[j])) / (local_sum)
        lr = 0.01
        for k in range(10):
            diff_weit = (y[k] - current_target[k])*current_row
            ini_weit[k] = ini_weit[k] - (lr*diff_weit)
    return ini_weit

def pred(ini_weit, x_test):
    a = np.zeros((10))
    y_pred =  np.zeros(x_test.shape[0])
    for row in range(x_test.shape[0]):
        current_row = x_test[row]
        local_sum = 0
        Bias = 0
        for i in range(10):
            a[i] = np.dot(ini_weit[i],current_row) + Bias
            local_sum = local_sum + np.exp(a[i])
        y = np.zeros((10))
        
        for j in range(10):
            y[i] = (np.exp(a[j])) / (local_sum)
        y_pred[row] = np.argmax(y) 
    return y_pred

In [10]:
import pickle
import gzip
import scipy.sparse
import numpy as np
from math import exp
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()
x_train = training_data[0]
x_target = training_data[1]
x_test = test_data[0]
test_target = test_data[1]
real_target = oneHotIt(x_target)
ini_weit = np.zeros([10,784],)
calc_weit = logistic_regression(x_train, real_target,ini_weit)
y_pred_logistic = pred(calc_weit, x_test)
#y_pred_logistic2 = pred(calc_weit, USPS_Mat)



out_mnist = confusion_matrix(y_pred_logistic, test_target)
print(" MNIST - confusion matrix using Logistic Regression :")
print(out_mnist)



#out_usps = confusion_matrix(y_pred_logistic2, USPS_Target)
#print(" USPS - confusion matrix using Logistic Regression :")
#print(out_usps)

#acc_usps = accuracy_score(y_pred_logistic2, USPS_Target)
#print("Accuracy using USPS is : ",+acc_usps)

acc_mnist = accuracy_score(y_pred_logistic, test_target)
print("Accuracy using MNIST is : ",+acc_mnist)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in double_scalars


 MNIST - confusion matrix using Logistic Regression :
[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [ 980 1135 1032 1010  982  892  958 1028  974 1009]]
Accuracy using MNIST is :  0.1009


In [14]:
y_pred_logistic2 = pred(calc_weit, USPS_Mat)
out_usps = confusion_matrix(y_pred_logistic2, USPS_Target)
print(" USPS - confusion matrix using Logistic Regression :")
print(out_usps)

acc_usps = accuracy_score(y_pred_logistic2, USPS_Target)
print("Accuracy using USPS is : ",+acc_usps)

 USPS - confusion matrix using Logistic Regression :
[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [2000 2000 1999 2000 2000 2000 2000 2000 2000 2000]]
Accuracy using USPS is :  0.10000500025001251


### DNN

In [185]:
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential
import pickle
import gzip
import scipy.sparse
import numpy as np
from math import exp
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()
x_train = training_data[0]
x_target = training_data[1]
x_test = test_data[0]
test_target = test_data[1]
(x_train, y_train), (x_test, y_test) = mnist.load_data()
num_classes=10
image_vector_size=28*28
x_train = x_train.reshape(x_train.shape[0], image_vector_size)
x_test = x_test.reshape(x_test.shape[0], image_vector_size)
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
image_size = 784 
model = Sequential()
model.add(Dense(units=32, activation='sigmoid', input_shape=(image_size,)))
model.add(Dense(units=num_classes, activation='softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=128, epochs=10,verbose=False,validation_split=.1)


loss,accuracy = model.evaluate(x_test, y_test, verbose=False)
y_pred_dense =  np.zeros(x_test.shape[0])
y_pred_inter = model.predict(x_test)
for i in range(y_pred_dense.shape[0]):
    y_pred_dense[i] = np.argmax(y_pred_inter[i])
    
loss2,accuracy2 = model.evaluate(USPS_Mat, USPS_Tar, verbose=False)
y_pred_dense2 =  np.zeros(USPS_Mat.shape[0])
y_pred_inter2 = model.predict(USPS_Mat)
for i in range(y_pred_dense2.shape[0]):
    y_pred_dense2[i] = np.argmax(y_pred_inter2[i])

In [210]:
out_usps = confusion_matrix(y_pred_dense2, USPS_Target)
acc_usps = accuracy_score(y_pred_dense2, USPS_Target)
print(" USPS - confusion matrix using DNN :")
print(out_usps)
print(" ")
print(acc_usps)

 USPS - confusion matrix using DNN :
[[ 289   17   21   12    4   27   52    3   32    4]
 [   0  177   12    2   22   13    1   72   15   61]
 [ 408  457 1483  200  103  389  829  486  364  198]
 [  72  583  238 1525  106  406  188  733  477  607]
 [  65   51   19    5  500   17   40    6   52   59]
 [ 103   50   75  130   57  828  178   13  374   32]
 [  81   29   33   13   27   89  589   20  106   12]
 [  32   41   26   31   62   62   12  199   20  297]
 [   8   16   15    7   33   20    2   28  119  114]
 [ 942  579   77   75 1086  149  109  440  441  616]]
 
0.31626581329066455


In [212]:
test_target = test_data[1]
out_mnist = confusion_matrix(y_pred_dense, test_target)
acc_mnist = accuracy_score(y_pred_dense, test_target)
print("MNIST - confusion matrix using DNN :")
print(out_mnist)
print(" ")
print(acc_mnist)



MNIST - confusion matrix using DNN :
[[ 959    0   17    4    2   13   16    4    9    8]
 [   0 1111    3    5    0    5    3   11   10    5]
 [   3    1  916   29    3    5    5   26    7    4]
 [   0    3   11  859    1   39    0    3   17    4]
 [   0    1   11    1  908   14   11   10   14   65]
 [   5    0    0   48    0  724    9    0   28   11]
 [   7    4   22    5   15   28  911    1   15    1]
 [   2    2   14   19    1   14    0  913   16   18]
 [   4   13   34   31    7   36    3    4  848   10]
 [   0    0    4    9   45   14    0   56   10  883]]
 
0.9032


In [180]:
y_test

(10000, 10)

### CNN

In [15]:
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential
import pickle
import gzip
import scipy.sparse
import numpy as np
from math import exp
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dropout
from keras.layers.core import Dense
from keras import backend as K
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()
x_train = training_data[0]
x_target = training_data[1]
x_test = test_data[0]
(x_train, y_train), (x_test, y_test) = mnist.load_data()
num_classes=10
image_vector_size=28*28
x_train = x_train.reshape(x_train.shape[0], 28,28,1)
x_test = x_test.reshape(x_test.shape[0], 28,28,1)
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
image_size = 784
chanDim = 1
model = Sequential()
# CONV => RELU => POOL layer set
model.add(Conv2D(32, (3, 3), padding="same",input_shape=(28,28,1)))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

# (CONV => RELU) * 2 => POOL layer set
model.add(Conv2D(64, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(Conv2D(64, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))


# (CONV => RELU) * 3 => POOL layer set
model.add(Conv2D(128, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(Conv2D(128, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(Conv2D(128, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
        

# first (and only) set of FC => RELU layers
model.add(Flatten())
model.add(Dense(512))
model.add(Activation("relu"))
model.add(BatchNormalization())
model.add(Dropout(0.5))
 
# softmax classifier
model.add(Dense(units=num_classes, activation='softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=128, epochs=2,verbose=False,validation_split=.1)


loss,accuracy = model.evaluate(x_test, y_test, verbose=False)
y_pred_con =  np.zeros(x_test.shape[0])
y_pred_inter = model.predict(x_test)
for i in range(y_pred_con.shape[0]):
    y_pred_con[i] = np.argmax(y_pred_inter[i])
    
    
USPS_Mat = USPS_Mat.reshape(USPS_Mat.shape[0], 28,28,1)
loss2,accuracy2 = model.evaluate(USPS_Mat, USPS_Tar, verbose=False)
y_pred_con2 =  np.zeros(USPS_Mat.shape[0])
y_pred_inter2 = model.predict(USPS_Mat)
for i in range(y_pred_con2.shape[0]):
    y_pred_con2[i] = np.argmax(y_pred_inter2[i])
    
    
out_usps = confusion_matrix(y_pred_con2, USPS_Target)
print(" USPS - confusion matrix using CNN :")
print(out_usps)


test_target = test_data[1]
out_mnist = confusion_matrix(y_pred_con, test_target)
print("MNIST - confusion matrix using CNN :")
print(out_mnist)

 USPS - confusion matrix using CNN :
[[   0    0    0    0    0    0    0    0    0    0]
 [2000 2000 1999 2000 2000 2000 2000 2000 2000 2000]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]]
MNIST - confusion matrix using CNN :
[[ 972    0    5    0    1    1    7    1    3    4]
 [   0 1130    0    0    0    0    4    5    0    4]
 [   2    3 1012    1    1    0    1   12    1    1]
 [   0    1    8  995    0    1    0    5   10    5]
 [   0    0    0    0  947    0    2    0    1    5]
 [   3    0    0   12    0  889   16    1   19   17]
 [   1    1    0    0    4    1  926    0    0    0]
 [   1    0    1    1   

In [252]:
test_target = test_data[1]
out_mnist = confusion_matrix(y_pred_con, test_target)
print("MNIST - confusion matrix using CNN :")
print(out_mnist)
acc_mnist = accuracy_score(y_pred_con, test_target)
print(" ")
print(acc_mnist)


MNIST - confusion matrix using CNN :
[[ 973    0    3    0    1    1    7    1    3    4]
 [   0 1130    0    0    1    0    5    5    0    4]
 [   1    4 1019    2    1    0    4   15    4    0]
 [   0    1    3  991    0    4    0    4    2    6]
 [   0    0    0    0  950    0    3    0    2    5]
 [   1    0    0   11    0  885    5    1    7    7]
 [   1    0    0    0    5    1  930    0    1    0]
 [   1    0    3    2    1    1    0  988    2    6]
 [   3    0    4    4    4    0    4    2  948    3]
 [   0    0    0    0   19    0    0   12    5  974]]
 
0.9788


In [253]:
USPS_Mat = USPS_Mat.reshape(USPS_Mat.shape[0], 28,28,1)
loss2,accuracy2 = model.evaluate(USPS_Mat, USPS_Tar, verbose=False)
y_pred_con2 =  np.zeros(USPS_Mat.shape[0])
y_pred_inter2 = model.predict(USPS_Mat)
for i in range(y_pred_con2.shape[0]):
    y_pred_con2[i] = np.argmax(y_pred_inter2[i])
    
    
out_usps = confusion_matrix(y_pred_con2, USPS_Target)
print(" USPS - confusion matrix using CNN :")
print(out_usps)
acc_mnist = accuracy_score(y_pred_con2, USPS_Target)
print(" ")
print(acc_mnist)

 USPS - confusion matrix using CNN :
[[   0    0    0    0    0    0    0    0    0    0]
 [2000 2000 1999 2000 2000 2000 2000 2000 2000 2000]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]]
 
0.10000500025001251


In [198]:
USPS_Mat.shape[0]

19999

In [199]:
x_test.shape[0]

10000

### Majority Voting

In [254]:
def maj_vote(a,b,d):
    local = []
    new_list = []
    maj_rep = np.zeros([10000],)
    for i in range(10000):
        local.append(a[i])
        local.append(b[i])
        #local.append(c[i])
        local.append(d[i])
        counts = np.bincount(local)
        temp = np.argmax(counts)
        new_list.append(temp)
    #print(new_list)
    return new_list
    
def maj_vote2(a,b,d):
    local = []
    new_list = []
    #maj_rep = np.zeros([10000],)
    for i in range(19999):
        local.append(a[i])
        local.append(b[i])
        #local.append(c[i])
        local.append(d[i])
        counts = np.bincount(local)
        temp = np.argmax(counts)
        new_list.append(temp)
    return new_list

In [255]:
new_list = np.zeros([10000],)
new_list2 = np.zeros([19999],)
new_list = maj_vote(y_pred_dense,y_pred_con,y_pred_logistic)
new_list2 = maj_vote2(y_pred_dense2,y_pred_con2,y_pred_logistic2)

In [256]:
out_usps = confusion_matrix(new_list2, USPS_Target)
print(" USPS - confusion matrix using majority vote :")
print(out_usps)
acc_usps = accuracy_score(new_list2, USPS_Target)
print(" ")
print(acc_usps)

 USPS - confusion matrix using majority vote :
[[   1    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [1999 2000 1999 2000 2000 2000 2000 2000 2000 2000]]
 
0.10005500275013751


In [257]:
out_mnist = confusion_matrix(new_list, test_target)
print(" USPS - confusion matrix using majority vote :")
print(out_usps)
acc_mnist = accuracy_score(new_list, test_target)
print(" ")
print(acc_mnist)

 USPS - confusion matrix using majority vote :
[[   1    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [1999 2000 1999 2000 2000 2000 2000 2000 2000 2000]]
 
0.1011
